import { Voucher, VoucherState } from '@perx/core';

export const mock: Voucher[] = [
    {
        id: 123,
        reward: {
            id: 123,
            name: '',
            description: '',
            subtitle: '',
            validFrom: new Date(),
            validTo: new Date(),
            sellingFrom: new Date(),
            rewardThumbnail: '',
            rewardBanner: '',
            merchantImg: '',
            rewardPrice: [],
            merchantId: 1,
            merchantName: '',
            merchantWebsite: '',
            termsAndConditions: '',
            howToRedeem: '',
            redemptionType: null,
            categoryTags: [],
            inventory: null,
          },
        state: VoucherState.issued,
        expiry: new Date(),
    },
    {
        id: 124,
        reward: {
            id: 124,
            name: '',
            description: '',
            subtitle: '',
            validFrom: new Date(),
            validTo: new Date(),
            sellingFrom: new Date(),
            rewardThumbnail: '',
            rewardBanner: '',
            merchantImg: '',
            rewardPrice: [],
            merchantId: 1,
            merchantName: '',
            merchantWebsite: '',
            termsAndConditions: '',
            howToRedeem: '',
            redemptionType: null,
            categoryTags: [],
            inventory: null,
          },
        state: VoucherState.issued,
        expiry: new Date(),
    },
    {
        id: 125,
        reward: {
            id: 125,
            name: '',
            description: '',
            subtitle: '',
            validFrom: new Date(),
            validTo: new Date(),
            sellingFrom: new Date(),
            rewardThumbnail: '',
            rewardBanner: '',
            merchantImg: '',
            rewardPrice: [],
            merchantId: 1,
            merchantName: '',
            merchantWebsite: '',
            termsAndConditions: '',
            howToRedeem: '',
            redemptionType: null,
            categoryTags: [],
            inventory: null,
          },
        state: VoucherState.issued,
        expiry: new Date(),
    },
];
