apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: microsite-apps-ng-lint
  namespace: build
spec:
  resources:
    inputs:
      - name: workspace
        type: git
        targetPath: project
  stepTemplate:
    image: circleci/node:10
    resources: &resources
      limits:
        cpu: 3
        memory: "4Gi"
      requests:
        cpu: 1.5
        memory: "3Gi"
        # ephemeral-storage: "1Gi"
  steps:
    - name: yarn-install
      workingDir: "/workspace/project"
      command: ["yarn", "install"]
      resources: *resources
    - name: run-lint
      workingDir: "/workspace/project"
      command: ["yarn", "run", "lint-ci"]
      resources: *resources

