export const LIST_CATEGORY = [
    {
        id:1,
        image:'./assets/images/img-bdorewards.svg',
        title:'BDO Rewards',
        code:'bdoRewards',
        subCategories:[{
            label:'Emerald ',
            code:"emerald",
        },
        {
            label:'Sapphire',
            code:"sapphire",
        },
        {
            link:'/catalog-page',
            label:'Diamond',
            code:"diamond",
        }]
    },
    {
        id:2,
        image:'./assets/images/img-creditcard.svg',
        title:'Credit Card',
        code:'creditCard',
        subCategories:[{
            link:'#',
            label:'Card Exclusives',
            code:"cardExclusives",
        },
        {
            link:'#',
            label:'Essentials',
            code:"essentials",
        },
        {
            link:'#',
            label:'Installment',
            code:"installment",
        },
        {
            link:'#',
            label:'Shop',
            code:"shop",
        },
        {
            link:'#',
            label:'More',
        }]
    },
    {
        id:3,
        image:'./assets/images/img-debitcard.svg',
        title:'Debit Card',
        content:'',
        code:'debitCard',
        subCategories:[{
            link:'#',
            label:'Card Exclusives',
            code:"cardExclusives",
        },
        {
            link:'#',
            label:'Essentials',
            code:"essentials",
        },
        {
            link:'#',
            label:'Shop',
            code:"shop",
        },
        {
            link:'#',
            label:'Dine',
            code:"dine",
        },
        {
            link:'#',
            label:'More'
        }]
    }
];