import { Voucher, VoucherState, RedemptionType } from '@perx/core';

export const vouchers: Voucher[] = [
    {
    id: 1,
    rewardId: 1,
    state: VoucherState.issued,
    name: '10% OFF Total Bill',
    redemptionType: RedemptionType.qr,
    thumbnailImg: 'https://picsum.photos/50/50?random=1',
    rewardBanner: '',
    merchantImg: '',
    merchantName: '',
    expiry: null,
    description: [],
    redemptionSuccessTxt: '',
    redemptionSuccessImg: '',
  },
  {
    id: 1,
    rewardId: 1,
    state: VoucherState.issued,
    name: 'Free Frapuccino',
    redemptionType: RedemptionType.qr,
    thumbnailImg: 'https://picsum.photos/50/50?random=2',
    rewardBanner: '',
    merchantImg: '',
    merchantName: '',
    expiry: null,
    description: [],
    redemptionSuccessTxt: '',
    redemptionSuccessImg: '',
  },
  {
    id: 1,
    rewardId: 1,
    state: VoucherState.expired,
    name: '10% OFF Total Bill',
    redemptionType: RedemptionType.qr,
    thumbnailImg: 'https://picsum.photos/50/50?random=3',
    rewardBanner: '',
    merchantImg: '',
    merchantName: '',
    expiry: null,
    description: [],
    redemptionSuccessTxt: '',
    redemptionSuccessImg: '',
  },
  {
    id: 1,
    rewardId: 1,
    state: VoucherState.redeemed,
    name: 'Free Frapuccino',
    redemptionType: RedemptionType.qr,
    thumbnailImg: 'https://picsum.photos/50/50?random=4',
    rewardBanner: '',
    merchantImg: '',
    merchantName: '',
    expiry: null,
    description: [],
    redemptionSuccessTxt: '',
    redemptionSuccessImg: '',
  }
];
