// tslint:disable
export class Engagement {
  public id: number;
  public current_type: string;
  public urn: string;
  public created_at: string;
  public updated_at: string;
  public game_type: string;
  public title: string;
  public description: string;
  public image_url: string;
  public attributes_type: string;
  public fontName: string;
  public fontColor: string;
  public headerColor: string;
  public headerTitle: string;
  public headlineText: string;
  public mainShapeType: string;
  public backgroundColor: string;
  public headerLogoImage: string;
  public subHeadlineText: string;
  public callToActionText: string;
  public loadingHeadlineText: string;
  public loadingSubHeadlineText: string;
  public background: string;
  public cardBackground: string;
  public buttonText?: string;
  constructor(data: IEngagement) {
    this.id = data.id;
    this.current_type = data.type;
    this.urn = data.attributes.urn;
    this.created_at = data.attributes.created_at;
    this.updated_at = data.attributes.updated_at;
    this.title = data.attributes.title;
    this.game_type = data.attributes.game_type;
    this.description = data.attributes.description;
    this.image_url = data.attributes.image_url;
    this.attributes_type = data.attributes.type;
    this.fontName = data.attributes.display_properties.fontName;
    this.fontColor = data.attributes.display_properties.fontColor;
    this.headerColor = data.attributes.display_properties.headerColor;
    this.headerTitle = data.attributes.display_properties.headerTitle;
    this.headlineText = data.attributes.display_properties.headlineText;
    this.mainShapeType = data.attributes.display_properties.mainShapeType;
    this.backgroundColor = data.attributes.display_properties.backgroundColor;
    this.headerLogoImage = data.attributes.display_properties.headerLogoImage;
    this.subHeadlineText = data.attributes.display_properties.subHeadlineText;
    this.callToActionText = data.attributes.display_properties.callToActionText;
    this.loadingHeadlineText = data.attributes.display_properties.loadingHeadlineText;
    this.loadingSubHeadlineText = data.attributes.display_properties.loadingSubHeadlineText;
    this.background = data.attributes.display_properties.background;
    this.cardBackground = data.attributes.display_properties.cardBackground;
    this.buttonText = data.attributes.display_properties.buttonText;
  }
}
