name: lint
on: [pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # checkout is not needed since it's performed inside tekton taskrun
      # - uses: actions/checkout@master
      - uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: ${{ secrets.BUILDER_KUBE_CONFIG }}
      - name: Create tekton task
        run: |
          cat <<EOT | kubectl -n build create -f - --output=jsonpath={.metadata.name} | xargs -I {} echo "::set-env name=TASKRUN_NAME::{}"
          apiVersion: tekton.dev/v1alpha1
          kind: TaskRun
          metadata:
            generateName: microsite-apps-ng-lint-
          spec:
            serviceAccount: tekton
            taskRef:
              name: microsite-apps-ng-lint
            inputs:
              resources:
                - name: workspace
                  resourceSpec:
                    type: git
                    params:
                      - name: url
                        value: git@github.com:PerxTech/microsite-apps-ng.git
                      - name: revision
                        value: ${{ github.sha }}
            podTemplate:
              securityContext:
                runAsUser: 0
                runAsGroup: 0
              nodeSelector:
                dedicated: build
              tolerations:
                - key: "dedicated"
                  value: "build"
                  effect: "NoSchedule"
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                        - key: machine-type
                          operator: In
                          values:
                          - highcpu
          EOT
      - name: Download tekton cli
        run: |
          curl -L https://github.com/tektoncd/cli/releases/download/v0.4.0/tkn_0.4.0_Linux_x86_64.tar.gz \
          | sudo tar xzv -C /usr/local/bin tkn
      - name: Wait for tekton task running
        run: |
          echo "Wait for tekton task: ${TASKRUN_NAME}"
          NEXT_WAIT_TIME=0
          until [ "$(kubectl -n build get taskrun ${TASKRUN_NAME} --output=jsonpath='{.status.conditions[0].reason}')" = "Running" ] || [ $NEXT_WAIT_TIME -eq 300 ]; do
            sleep $(( NEXT_WAIT_TIME+=5 ))
          done
      - name: Stream task log
        run: |
          echo "Tekton taskrun name: ${TASKRUN_NAME}"
          tkn -n build taskrun logs -f ${TASKRUN_NAME}
      - name: Check task result
        run: |
            REASON=$(kubectl -n build get taskrun ${TASKRUN_NAME} --output=jsonpath={.status.conditions[0].reason})
            if [ "$REASON" != "Succeeded" ]; then
              echo "Taskrun not succeeded, fail the job"
              exit 1
            fi
