name: lint
on: [pull_request]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          REGEX="[[:alpha:]]+[[:digit:]]*-[[:digit:]]+"
          if [[ ! ${GITHUB_HEAD_REF} =~ ${REGEX} ]]; then
            echo "Branch name ${GITHUB_HEAD_REF} doesn't meet naming convention: ${REGEX}"
            exit 1
          fi

      - name: Cancel redundant jobs
        uses: technote-space/auto-cancel-redundant-job@v1

      - name: Set kubecontext
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.AWS_BUILDER_KUBE_CONFIG }}

      - name: Download tekton cli and install parallel
        env:
          TEKTON_CLI_VERSION: 0.18.0
        run: |
          curl -L https://github.com/tektoncd/cli/releases/download/v${TEKTON_CLI_VERSION}/tkn_${TEKTON_CLI_VERSION}_Linux_x86_64.tar.gz \
          | sudo tar xzv -C /usr/local/bin tkn
          sudo apt-get install -y parallel

          # Set tekton label
          LABEL=$(echo ${GITHUB_REF//[^0-9a-zA-Z-_\.]/-} | cut -c-60)
          # Workaround to ensure label name ended with alphanumeric char
          LABEL+=0
          echo "TEKTON_LABEL=${LABEL}" >> "${GITHUB_ENV}"

      - name: Remove existing tasks
        run: |
          EXISTING_TASKS=$(kubectl -n build get taskrun -l github.ref=${TEKTON_LABEL},tekton.dev/task=microsite-apps-ng-lint -o=name)
          if [ ${#EXISTING_TASKS[@]} -ne 0 ]; then
            parallel kubectl -n build delete --ignore-not-found {} ::: ${EXISTING_TASKS[@]}
          else
            echo "No existing taskruns"
          fi

      - name: Create tekton task
        run: |
          TEKTON_TASK=$(cat <<EOT | kubectl -n build create -f - --output=jsonpath={.metadata.name}
          apiVersion: tekton.dev/v1beta1
          kind: TaskRun
          metadata:
            generateName: microsite-apps-ng-lint-
            labels:
              github.ref: ${TEKTON_LABEL}
              task: lint
            annotations:
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          spec:
            serviceAccountName: tekton
            taskRef:
              name: microsite-apps-ng-lint
            resources:
              inputs:
                - name: workspace
                  resourceSpec:
                    type: git
                    params:
                      - name: url
                        value: git@github.com:PerxTech/microsite-apps-ng.git
                      - name: revision
                        value: ${{ github.ref }}
            podTemplate:
              securityContext:
                runAsUser: 0
                runAsGroup: 0
              nodeSelector:
                dedicated: cpu-spot-pool
              tolerations:
                - key: "dedicated"
                  value: "build"
                  effect: "NoSchedule"
          EOT
          )
          echo "Task: ${TEKTON_TASK}"
          echo "TASKRUN_NAME=${TEKTON_TASK}" >> "${GITHUB_ENV}"

      - name: Check task result
        run: |
          start=$SECONDS
          until [[ $(( SECONDS - start )) -gt 1200 ]]; do
            REASON=$(kubectl -n build get taskrun ${TASKRUN_NAME} --output=jsonpath='{.status.conditions[0].reason}')
            STATUS=$(kubectl -n build get taskrun ${TASKRUN_NAME} --output=jsonpath='{.status.conditions[0].status}')
            if [[ "${REASON}" = "Succeeded" ]] && [[ "${STATUS}" = "True" ]]; then
              exit 0
            fi
            if [[ "${REASON}" = "Failed" ]] && [[ "${STATUS}" = "False" ]]; then
              echo "Taskrun ${TASKRUN_NAME} is failed, fail the job"
              exit 1
            fi
            echo "Taskrun ${TASKRUN_NAME} reason is ${REASON}, status is ${STATUS}"
            sleep 20
            echo "Running for $(( SECONDS - start )) seconds"
          done
          if [[ $(( SECONDS - start )) -gt 1200 ]]; then
            echo ">>>> Timeout hit <<<<"
            exit 1
          fi

      - name: Display dashboard link
        if: always()
        run: |
          for TASKRUN_NAME in ${TEKTON_TASKS[@]}; do
            TASKRUN_STATUS=$(kubectl -n build get taskrun ${TASKRUN_NAME} --output=jsonpath='{.status.conditions[0].reason}')
            if [ "${TASKRUN_STATUS}" = "Failed" ]; then
              echo ">>>> Taskrun ${TASKRUN_NAME} status is ${TASKRUN_STATUS} <<<<"
              echo "::error ::https://tekton-dashboard.perxtech.io/#/namespaces/build/taskruns/${TASKRUN_NAME}/"
            fi
          done

      - name: Taskruns cleanup
        if: always()
        run: |
          TASKRUN_STATUS=$(kubectl -n build get taskrun ${TASKRUN_NAME} --output=jsonpath='{.status.conditions[0].reason}')
          echo ">>>> Taskrun ${TASKRUN_NAME} status is ${TASKRUN_STATUS} <<<<"
          if [ "${TASKRUN_STATUS}" = "Succeeded" ]; then
            echo ">>>> Deleting succeeded taskrun ${TASKRUN_NAME} <<<<"
            tkn -n build taskrun delete ${TASKRUN_NAME}
          fi
